# -*- coding: utf-8 -*-
"""
PHASE 0 — reality-check of the recreation pipeline (separation by ear + objective).

Takes a 45s clip of DarkPsy_v9_SURGE_XT.wav (the ORDER section), runs Demucs to
separate it, runs librosa for BPM/key, and -- because this track was generated by
OUR engine -- compares Demucs' stems against the GROUND-TRUTH stems in stems_v9/.

Outputs WAVs to forja/recreation_out/phase0/ for Juan to LISTEN, plus a printed
report: BPM detected (truth 150), key (truth E), and per-stem similarity to truth.
"""
import os, sys, glob
import numpy as np
from scipy.io import wavfile
import librosa

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IN = "C:/Users/Juan/Desktop/DarkPsy_v9_SURGE_XT.wav"
GT_DIR = os.path.join(REPO, "stems_v9")
OUT = os.path.join(REPO, "forja", "recreation_out", "phase0")
os.makedirs(OUT, exist_ok=True)

SR = 44100
BPM = 150
BAR = (60.0 / BPM) * 4
START_BAR, END_BAR = 91, 120            # the ORDER window we know well
T0, T1 = START_BAR * BAR, END_BAR * BAR  # ~145.6s .. 192s

def read_wav(path):
    sr, d = wavfile.read(path)
    if d.ndim == 1:
        d = np.column_stack([d, d])
    if d.dtype == np.int16:
        d = d.astype(np.float64) / 32768.0
    elif d.dtype == np.int32:
        d = d.astype(np.float64) / 2147483648.0
    else:
        d = d.astype(np.float64)
    return sr, d

def write_wav(path, stereo):
    x = np.clip(stereo, -1, 1)
    wavfile.write(path, SR, (x * 32767).astype(np.int16))

def mono(x):
    return x.mean(axis=1) if x.ndim > 1 else x

def corr(a, b):
    """Normalized correlation of two mono signals (timbre/content similarity)."""
    n = min(len(a), len(b))
    a, b = a[:n], b[:n]
    a = a - a.mean(); b = b - b.mean()
    da, db = np.sqrt((a * a).sum()), np.sqrt((b * b).sum())
    if da < 1e-9 or db < 1e-9:
        return 0.0
    return float((a * b).sum() / (da * db))

def spec_corr(a, b):
    """Phase-insensitive timbre/content similarity via log-mel spectrogram correlation."""
    n = min(len(a), len(b))
    a, b = a[:n].astype(np.float32), b[:n].astype(np.float32)
    ma = librosa.power_to_db(librosa.feature.melspectrogram(y=a, sr=SR, n_mels=64))
    mb = librosa.power_to_db(librosa.feature.melspectrogram(y=b, sr=SR, n_mels=64))
    f = min(ma.shape[1], mb.shape[1])
    va, vb = ma[:, :f].ravel(), mb[:, :f].ravel()
    va = va - va.mean(); vb = vb - vb.mean()
    d = np.sqrt((va * va).sum()) * np.sqrt((vb * vb).sum())
    return 0.0 if d < 1e-9 else float((va * vb).sum() / d)

def band_profile(x):
    f = np.abs(np.fft.rfft(x)); fr = np.fft.rfftfreq(len(x), 1 / SR)
    tot = (f ** 2).sum() + 1e-12
    out = {}
    for nm, lo, hi in [("sub", 20, 60), ("bass", 60, 200), ("lowmid", 200, 600),
                       ("mid", 600, 2000), ("himid", 2000, 6000), ("air", 6000, 20000)]:
        m = (fr >= lo) & (fr < hi)
        out[nm] = (f[m] ** 2).sum() / tot * 100
    return out

print("=" * 64)
print(" PHASE 0 — recreation reality-check")
print("=" * 64)
if not os.path.exists(IN):
    print(f"  INPUT NO ENCONTRADO: {IN}")
    sys.exit(1)

# 1) extract the clip
sr, full = read_wav(IN)
s0, s1 = int(T0 * SR), int(T1 * SR)
clip = full[s0:min(s1, len(full))]
clip_path = os.path.join(OUT, "00_clip.wav")
write_wav(clip_path, clip)
print(f"\n  Clip: bars {START_BAR}-{END_BAR}  ({len(clip)/SR:.1f}s) -> {clip_path}")

# 2) Demucs separation (via CLI subprocess — stable across demucs builds)
print("\n  Separando con Demucs (htdemucs, CPU)... puede tardar ~1-3 min")
import subprocess, shutil
MODEL = "htdemucs"
try:
    cmd = [sys.executable, "-m", "demucs", "-n", MODEL, "-d", "cpu",
           "-o", OUT, "--filename", "{stem}.wav", clip_path]
    subprocess.run(cmd, check=True)
    demux_dir = os.path.join(OUT, MODEL)
    for stem in ["drums", "bass", "other", "vocals"]:
        src = os.path.join(demux_dir, f"{stem}.wav")
        if os.path.exists(src):
            shutil.copy(src, os.path.join(OUT, f"demucs_{stem}.wav"))
            print(f"    demucs_{stem}.wav")
except Exception as e:
    print(f"  ERROR demucs: {e}")
    sys.exit(1)

# 3) librosa BPM / key
print("\n  Analizando BPM/tono con librosa...")
try:
    import librosa
    y = mono(clip).astype(np.float32)
    tempo, _ = librosa.beat.beat_track(y=y, sr=SR, start_bpm=145)
    tempo = float(np.atleast_1d(tempo)[0])
    chroma = librosa.feature.chroma_cqt(y=y, sr=SR).mean(axis=1)
    pcs = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]
    root = pcs[int(np.argmax(chroma))]
    print(f"    BPM detectado: {tempo:.1f}   (verdad: 150)")
    print(f"    Root detectado: {root}   (verdad: E)")
except Exception as e:
    print(f"  ERROR librosa: {e}")

# 4) compare Demucs stems vs ground-truth (sliced to same window)
print("\n  Comparando Demucs vs verdad (stems_v9/):")
def gt_slice(*names):
    acc = None
    for n in names:
        cands = glob.glob(os.path.join(GT_DIR, f"*{n}*.wav"))
        if not cands:
            continue
        _, d = read_wav(cands[0])
        seg = d[s0:min(s1, len(d))]
        acc = seg if acc is None else acc[:len(seg)] + seg[:len(acc)]
    return acc

pairs = [
    ("bass",  "demucs_bass.wav",  ("bass",)),
    ("drums", "demucs_drums.wav", ("kick", "drums")),
    ("other (blob)", "demucs_other.wav", ("lead", "acid", "pad", "fm_texture", "fx")),
]
for label, dfile, gt_names in pairs:
    dp = os.path.join(OUT, dfile)
    gt = gt_slice(*gt_names)
    if not os.path.exists(dp) or gt is None:
        print(f"    {label}: (falta dato)")
        continue
    _, dwav = read_wav(dp)
    sc = spec_corr(mono(dwav), mono(gt))
    print(f"    {label:14s} vs {'+'.join(gt_names):28s}  spec_corr={sc:+.2f}")

print("\n  ESCUCHÁ estos archivos para juzgar la separación:")
for f in sorted(glob.glob(os.path.join(OUT, "demucs_*.wav"))):
    print(f"    {f}")
print(f"\n  (clip original: {clip_path})")
print("  Done.")
